@ECHO OFF
RMDIR /S /Q "..\Common\bin"
RMDIR /S /Q "..\Common\obj"
RMDIR /S /Q "..\PlaydarDaemon\bin"
RMDIR /S /Q "..\PlaydarDaemon\obj"
RMDIR /S /Q "..\PluginAPI\bin"
RMDIR /S /Q "..\PluginAPI\obj"
RMDIR /S /Q "..\Plugins\PlayerPlugin\bin"
RMDIR /S /Q "..\Plugins\PlayerPlugin\obj"
RMDIR /S /Q "..\TrayApp\bin"
RMDIR /S /Q "..\TrayApp\obj"
RMDIR /S /Q "Temp"
RMDIR /S /Q "Utils\erlini\bin"
RMDIR /S /Q "Utils\erlini\obj"
